name: neo_ice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  image_picker: 
  sqlite3: 
  ffi: 
  drift: 
  drift_flutter: 
  path_provider: 
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  google_fonts:
  fl_chart: ^0.70.1 
  flex_color_scheme: ^8.0.2
  path: 
  intl:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2

flutter_native_splash:
  color: "#b3ddda"
  image: "assets/images/splash.jpeg"
  image_dark: "assets/images/splash.jpeg"
  android: true
  web: false
  ios: false

flutter_icons:
  android: true
  image_path: "assets/images/default.png"
  adaptive_icon_background: "#b3ddda"
  adaptive_icon_foreground: "assets/images/default.png"

dev_dependencies:
  drift_dev: 
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
